version: '3'
services:
  web:
    build: .
    container_name: complex_app
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
    - ${app_path_host}:${app_path_container}
    ports:
    - 8080:80
    working_dir: ${app_path_container}
    networks:
      static-network:
        ipv4_address: 172.20.128.1
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
